require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.treesitter"
require "user.markdownconfigs"
require "user.autopairsconfigs"
require "user.keymaps"
